apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: quant-ai
  labels:
    app: quant-ai-consumer
spec:
  type: NodePort
  selector:
    app: quant-ai-consumer
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      nodePort: 30002
